 server:
  port: 8081
  servlet:
    context-path: /ruoyi-api
 spring:
  application:
    name: ten-base
  datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://localhost:3306/ruoyi_sys?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
   username: root
   password: 1234
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true
 mybatis:
   mapper-locations: classpath:mybatis/mapper/*SQL.xml
 pagehelper:
    helperDialect: MYSQL
    reasonable: true
    supportMethodsArguments: true
    pageSizeZero: true
    params: count=countSql



